Core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('/posts', views.PostsView.as_view(), name='posts'),
    path('/add', views.AddView.as_view(), name='add'),
    path('/edit/<int:pk>', views.EditView.as_view(), name='edit'),
    path('delete/<int:pk>', views.Delete.as_view(), name='delete'),
    path('<slug:slug>/', views.SingleView.as_view(), name='single'),
]

notesproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Core.urls', 'core'), namespace='core'))
]

Core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Core(models.Model):
    title = models.CharField(max_length=255, null=False)
    description = models.CharField(max_length=255, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='core')
    slug = models.SlugField(max_length=32, unique=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('core:single', args=[self.slug])

    class Meta:
        db_table = 'notes'
        ordering = ['-published']
        verbose_name = 'Core'
        verbose_name_plural = 'Cores'

    def __str__(self):
        return self.title

Core/forms.py
from django import forms
from .models import Core


class PostForm(forms.ModelForm):
    class Meta:
        model = Core
        fields = '__all__'

Core/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from .models import Core

app_name = 'core'


class IndexView(ListView):
    model = Core
    template_name = 'core/index.html'
    context_object_name = 'index'


class SingleView(DetailView):
    model = Core
    template_name = 'core/single.html'
    context_object_name = 'post'


class PostsView(ListView):
    model = Core
    template_name = 'core/posts.html'
    context_object_name = 'post_list'


class AddView(CreateView):
    model = Core
    template_name = 'core/add.html'
    fields = '__all__'
    success_url = reverse_lazy('core:posts')


class EditView(UpdateView):
    model = Core
    template_name = 'core/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')


class Delete(DeleteView):
    model = Core
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')
    template_name = 'core/confirm-delete.html'

templates/core/add.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="container pt-5">
        <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field|add_class:'form-control' }}
                {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
                </div>
            {% endfor %}

        <div class="form-group">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok">Edit</span>
            </button>
            <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
        </div>
        </form>
    </div>
{% endblock %}

templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

{% include 'core/navbar.html' %}

{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% include 'core/footer.html' %}
</body>
</html>

templates/core/confirm-delete.html
{% extends 'core/base.html' %}
{% block content %}

    <div class="container pt-5">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want delete "{{ object }}"</p>
            <input type="submit" value="Confirm">
        </form>
    </div>

{% endblock %}

templates/core/edit.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block content %}

    <div class="container pt-5">
        <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field|add_class:'form-control' }}
                {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
                </div>
            {% endfor %}

        <div class="form-group">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok">Edit</span>
            </button>
            <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
        </div>
            
        </form>
    </div>

{% endblock %}

templates/core/footer.html
<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">

            <div class="col-12 col-md">Astana IT University
                <small class="d-block mb-3 text-muted">Be a part of the IT Future</small>
            </div>

            <div class="col-6 col-md">Admin
                <h5>Admin</h5>
                <ul class="list-unstyled text-small">
                    <li><a href="#" class="text-muted">Post Admin</a></li>
                </ul>
            </div>

            <div class="col-6 col-md">
                 <h5>About Us</h5>
                 <ul class="list-unstyled text-small">
                    <li><a href="#" class="text-muted">Home</a></li>
                </ul>
            </div>

            <div class="col-6 col-md">
                 <h5>Resources</h5>
                 <ul class="list-unstyled text-small">
                    <li><a href="https://gitlab.com/fancyguyfromatyrau/sqat-midterm-project/-/tree/main" class="text-muted">Gitlab</a></li>
                </ul>
            </div>

        </div>
    </footer>
</div>

templates/core/index.html
{% extends 'core/base.html'%}

{% block content %}
    <div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for item in index %}
        <div class="card mb-4 box-shadow">
            <img src="https://via.placeholder.com/150x100" alt="Card image cap" class="card-img-top">
        <div class="card-body">
            <h4><a href="{{ item.get_absolute_url }}"> {{ item.title }}</a></h4>
            <p class="card-text"></p>
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <small class="text-muted">{{ item.published }}</small>
                </div>
            </div>
        </div>
        </div>
            {% endfor %}

        </div>
    </div>
    </div>
{% endblock %}

templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a href="#" class="navbar-brand d-flex align-items-center">
        <svg class="bi bi-display-fill mr-2" width="1em" height="1em" viewBox="0 0 16 16"></svg>
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a href="/" class="nav-link">Home</a>
            </li>
            <li class="nav-item active">
                <a href="{% url 'core:posts' %}" class="nav-link">Manage Posts</a>
            </li>
        </ul>
    </div>
</nav>

templates/core/posts.html
{% extends 'core/base.html' %}

{% block content %}
    <nav class="navbar navbar-expand-lg navbar-light br-light">
        <div class="navbar-brand">Post Administration</div>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a href="{% url 'core:add' %}" class="nav-link">Add New</a>
                    </li>
                </ul>
            </div>
    </nav>

    <div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for post in post_list %}
                <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img src="https://via.placeholder.com/150x100" alt="Card image cap" class="card-img-top">
                    <div class="card-body">
                        <h4 class="lead"><a href="{% url 'core:single' post.pk %}" class="text-dark">{{ post.title }}</a></h4>
                        <p class="card-text"></p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{{ post.get_absolute_url }}" class="btn btn-sm btn-outline-primary">View</a>
                                <a href="{% url 'core:edit' post.pk %}" class="btn btn-sm btn-outline-secondary">Edit</a>
                                <a href="{% url 'core:delete' post.pk %}" class="btn btn-sm btn-outline-secondary">Delete</a>
                            </div>
                            <small class="text-muted">{{ post.published }}</small>
                        </div>
                    </div>
                </div>
                </div>
            {% endfor %}
        </div>
    </div>
    </div>
{% endblock %}

templates/core/single.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-12 pt-5">
            <img src="https://via.placeholder.com/150x100" alt="" class="card-img-top">
            <h2 class="pt-5">{{ post.title }}</h2>
            <p>{{ post.description }}</p>
        </div>
    </div>
    </div>
{% endblock %}

templates/core/update.html
<html>
 <head>
   <meta charset="utf-8">
   <title>Update Note</title>
 </head>
 <body>
   <h1>Update Note</h1>
   <form method="POST">
       {% csrf_token %}
       {{ form.as_p }}
       <input type="submit" value="Update">
   </form>
 </body>
</html>